### ISSUE TITLE
info download error

### ISSUE THREAD

**Issue by jiangnanan** [c1y2m3/FileSearch#3]
info download error  

code 299

无法获取 DBPass.Bin

**Comment by c1y2m3** [comment]
这个问题是出在std::string resultStr = webhttp((L"https://jihulab.com/bluesky1/padding/-/raw/main/README.md"));，
可能是目标无法访问这个链接，这是目标的网络问题，你可以把它修改为可访问的链接。

**Comment by jiangnanan** [comment]
起先我也感觉是这个问题，但是我单独提取 https://jihulab.com/bluesky1/padding/-/raw/main/README.md  访问确可以访问到上面的偏移基值，所以应该不是这块问题，就是不知是哪里问题？

**Comment by jiangnanan** [comment]
![image](https://user-images.githubusercontent.com/71580782/230012200-d340a074-a329-4755-9deb-3ab00374123a.png)

**Comment by jiangnanan** [comment]
然后我参考了一下另一套的代码C#写的  里头也是和您一样通过获取在线基值来完成 
![C#](https://user-images.githubusercontent.com/71580782/230012470-cb8a2a09-265f-4c42-ad28-89c95a1d07f2.PNG)
我特意调试了下的确可以正常获取，但是C++本人确定不是太了解，不知道怎么改动，望可以修正一下这个功能 谢谢

**Comment by jiangnanan** [comment]
不知道是不是webhttp 这个函数的问题 
![11](https://user-images.githubusercontent.com/71580782/230018306-8852c965-b171-4842-8461-ee4c1ea98629.PNG)

**Comment by jiangnanan** [comment]
我发现一个在win7系统上 会提示这个，我试过几台WIN7系统 都是提示 info download error   但是我放到WIN10系统上 确又可以，所以感觉是不是那个类的问题 麻烦作者修正下谢谢哈
